Atlanta/Atlanta/Controllers/OrdersController.cs
using Atlanta.DAL.Interfaces;
using Atlanta.Domain.Entity;
using Atlanta.Domain.Enums;
using Atlanta.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;

namespace Atlanta.Controllers;

[Authorize]
public class OrdersController : Controller
{
    private readonly IUserRepository _userRepository;
    private readonly IOrderRepository _orderRepository;
    private readonly IRoomRepository _roomRepository;
    private readonly IStaffRepository _staffRepository;

    public OrdersController(IUserRepository userRepository, IOrderRepository orderRepository, IRoomRepository roomRepository, IStaffRepository staffRepository)
    {
        this._userRepository = userRepository;
        this._orderRepository = orderRepository;
        this._roomRepository = roomRepository;
        this._staffRepository = staffRepository;
    }

    [HttpGet]
    public async Task<IActionResult> NewOrder()
    {
        var orderSearch = new OrderSearchViewModel();

        orderSearch.TypeRoom = new Dictionary<int, string>();
        orderSearch.TypeStaff = new Dictionary<int, string>();
        orderSearch.Location = new List<string>();
        var rooms = await this._roomRepository.SelectAsync();
        var staffs = await this._staffRepository.SelectAsync();
        rooms = rooms.Where(i => i.IsActive == true && i.IsWait == false);
        staffs = staffs.Where(i => i.IsActive == true && i.IsWait == false);
        var typeRoomListId = rooms.Select(i => i.IdTypeRoom);
        var typeStaffListId = staffs.Select(i => i.IdTypeStaff);

        var typeRoomList1 = new List<TypeRoom>();
        foreach (var id in typeRoomListId)
        {
            typeRoomList1.Add(await this._roomRepository.GetTypeRoom(id));
        }

        var typeRoomList = typeRoomList1.Distinct();
        var typeStaffList1 = new List<TypeStaff>();
        foreach (var id in typeStaffListId)
        {
            typeStaffList1.Add(await this._staffRepository.GetTypeStaff(id));
        }

        var typeStaffList = typeStaffList1.Distinct();
        var generalLocation =
            from r in rooms
            from s in staffs
            where r.Location == s.Location
            select r.Location;
        orderSearch.Location = generalLocation.ToList().Distinct().ToList();
        foreach (var typeRoom in typeRoomList)
        {
            orderSearch.TypeRoom.Add(typeRoom.IdTypeRoom, typeRoom.TypeName);
        }
        foreach (var typeStaff in typeStaffList)
        {
            orderSearch.TypeStaff.Add(typeStaff.IdTypeStaff, typeStaff.TypeName);
        }
        return View(orderSearch);
    }

    
    [HttpGet]
    public async Task<IActionResult> SearchForOrder(OrderSearchViewModel model)
    {
        var rooms = await this._roomRepository.SelectAsync();
        var room1 = rooms.Where(i => i.IdTypeRoom == model.TypeRoomValue && i.MaxAmountPeople >= model.MaxAmountPeople && i.Location == model.LocationValue).ToList();
        var staffs = await this._staffRepository.SelectAsync();
        var staff1 = staffs.Where(i => i.IdTypeStaff == model.TypeStaffValue && i.Location == model.LocationValue).ToList();

        var ordersWithDate = await this._orderRepository.SelectAsync();
        ordersWithDate = ordersWithDate.Where(i => i.DateOfEvent == model.DateOfEvent);
        foreach (var o in ordersWithDate)
        {
            var rom = room1.Where(i => i.IdRoom == o.IdRoom).ToList();
            if (rom.Any())
            {
                room1.Remove(rom.First());
            }

            var saf = staff1.Where(i => i.IdStaff == o.IdStaff).ToList();
            if (saf.Any())
            {
                staff1.Remove(saf.First());
            }
        }
        var order = new SecondOrderViewModel();
        order.Rooms = room1;
        order.Staffs = staff1;
        order.DateOfEvent = model.DateOfEvent;
        order.AmountPeople = model.MaxAmountPeople;
        order.Location = model.LocationValue;
        return View(order);
    }

    [HttpPost]
    public async Task<IActionResult> CreateOrder(SecondOrderViewModel model)
    {
        var order = new Orders();
        var room = await this._roomRepository.GetById(model.CurrentRoom);
        var staff = await this._staffRepository.GetById(model.CurrentStaff);
        order.IdStaff = staff.IdStaff;
        order.IdRoom = room.IdRoom;
        order.AllPrice = staff.Price + room.Price;
        order.DateOfEvent = model.DateOfEvent;
        var user = await this._userRepository.GetByEmail(User.Identity.Name);
        order.IdUser = user.IdUser;
        order.IdStatusOrder = StatusOrder.ReviewRoom_ReviewStaff;
        order.IsWait = true;
        await this._orderRepository.Add(order);
        return RedirectToAction("Index", "Home");
    }


    [HttpGet]
    public async Task<IActionResult> MyOrders()
    {
        var userOrder = await this._userRepository.GetByEmail(User.Identity.Name);
        var rooms = (await this._roomRepository.SelectAsync()).ToList()
            .Where(i => i.IsActive && i.IsWait == false).ToList();
        var response = (await this._orderRepository.SelectAsync()).ToList().Where(i => i.IdUser == userOrder.IdUser);
        List<OrderForUser> listForUser = new List<OrderForUser>();
        var staffs = (await this._staffRepository.SelectAsync()).ToList();
        foreach (var order in response)
        {
            var orderView = new OrderForUser();
            orderView.RoomView = rooms.FirstOrDefault(i => i.IdRoom == order.IdRoom).NameRoom;
            orderView.StaffView = staffs.FirstOrDefault(i => i.IdStaff == order.IdStaff).NameStaff;
            orderView.AllPrice = order.AllPrice;
            
            orderView.NameUser = userOrder.Email;
            orderView.IdOrder = order.IdOrder;
            orderView.IdStatusOrder = order.IdStatusOrder;
            orderView.IsWait = order.IsWait;
            listForUser.Add(orderView);
        }

        return View(listForUser);
    }
}

Atlanta/Atlanta/Controllers/ProfileController.cs
using Atlanta.DAL.Interfaces;
using Atlanta.Domain.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Atlanta.Controllers;

[Authorize]
public class ProfileController : Controller
{
    private readonly IUserRepository _userRepository;

    public ProfileController(IUserRepository userRepository)
    {
        this._userRepository = userRepository;
    }

    [HttpGet]
    public async Task <IActionResult> Index()
    {
        var currentUser = await this._userRepository.GetByEmail(User.Identity.Name);
        return View(currentUser);
    }

    [HttpPost]
    public async Task<IActionResult> Index(Users model)
    {
        await this._userRepository.Update(model);
        var currentUser = await this._userRepository.GetByEmail(User.Identity.Name);
        return View(currentUser);
    }

}

Atlanta/Atlanta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
    <link rel="stylesheet" href="~/css/adminpanel.css">
    <link rel="stylesheet" href="~/css/room.css">
</head>

<body>
<div class="container">
    <header>
        <div class="nav">
            <nav class="main-nav">
                <div class="nav-left">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <style>
                            .punks {
                                border: 1px solid gray;
                                border-radius: 3px;
                                font-size:14px;
                            }
                        </style>
                        <ul class="menu" style="z-index: 999;">
                            <li>
                                <a href="#" class="nav-item-link">Профіль</a>
                                <ul>
                                    <li>
                                        <a asp-action="Index" asp-controller="Profile" class="punks">Мій профіль</a>
                                    </li>
                                    
                                    @if (User.IsInRole("User"))
                                    {
                                        <li>
                                            <a asp-controller="Orders" asp-action="MyOrders" class="punks">Мої бронювання</a>
                                        </li>
                                        <li>
                                            <a asp-controller="Orders" asp-action="NewOrder" class="punks">Оформити бронювання</a>
                                        </li>
                                    }
                                    @if (User.IsInRole("RoomMan"))
                                    {
                                        <li>
                                            <a asp-action="AddRoom" asp-controller="Room" class="punks">Додати кімнату</a>
                                        </li>
                                        <li>
                                            <a asp-action="MyRooms" asp-controller="Room" class="punks">Мої кімнати</a>
                                        </li>
                                        <li>
                                            <a asp-action="MyOrders" asp-controller="Room" class="punks">Бронювання</a>
                                        </li>
                                    }
                                    @if (User.IsInRole("StaffMan"))
                                    {
                                        <li>
                                            <a asp-controller="Staff" asp-action="AddStaff" class="punks">Додати готель</a>
                                        </li>
                                        <li>
                                            <a asp-controller="Staff" asp-action="MyStaffs" class="punks">Мої готелі</a>
                                        </li>
                                        <li>
                                            <a asp-action="MyOrders" asp-controller="Staff" class="punks">Бронювання</a>
                                        </li>
                                    }
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <li>
                                            <a asp-action="Index" asp-controller="Admin" class="punks">Зміна ролей користувачів</a>
                                        </li>
                                        <li>
                                            <a asp-action="RoomApprove" asp-controller="Admin" class="punks">Підтверждення кімнат</a>
                                        </li>
                                        <li>
                                            <a asp-action="ViewRoom" asp-controller="Admin" class="punks">Перегляд кімнат</a>
                                        </li>
                                        <li>
                                            <a asp-action="StaffApprove" asp-controller="Admin" class="punks">Підтвердження готелів</a>
                                        </li>
                                        <li>
                                            <a asp-action="ViewStaff" asp-controller="Admin" class="punks">Перегляд готелів</a>
                                        </li>
                                        <li>
                                            <a asp-action="OrdersUser" asp-controller="Admin" class="punks">Бронювання</a>
                                        </li>
                                    }
                                        <li>
                                            <a asp-action="Logout" asp-controller="Account" class="punks">Вихід</a>
                                        </li>
                                </ul>
                            </li>
                        </ul>
                    }

                </div>
                <div class="nav-centered" style="margin-right: 0px">
                    <a asp-action="Index" asp-controller="Home" class="active">Atlanta Events</a>
                </div>
                <div class="nav-right">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <a asp-action="Login" asp-controller="Account" class="nav-item-link">Вхід</a>
                    }
                </div>
            </nav>
        </div>
    </header>
    <div class="content-box">
        @RenderBody()
    </div>
</div>
</body>
</html>